### ISSUE TITLE
Feature Request: Allow / Use Canvas for Participant Data Aggregation 

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/obsidian-quadro#1]
### Checklist

- [X] I have read the plugin's documentation.
- [X] The feature would be useful to more users than just me.

### Feature Requested

I think using Canvas pages for items (i.e. participants) would work well and be a good feature. I would like to have, for example:

Canvas -- Participant SG
- notes from my interview with SG (pdf file)
- coded transcript with my interview with SG 
- Audio of SG.
- Maybe individual cards with sections of interviews marching a query (or an embedded search). Canvas cards could be associated with codes if relevant. idk, just thinking out loud with this last one.

I imagine a template could be easily built to aid with this, but mostly wanted to get the canvas request in!

**Comment by chrisgrieser** [comment]
Hmm, could you elaborate a bit more how that is supposed to work? I mean, this plugin is mostly working with "textual" QDA, stuff like coding video or audio segments would require an entirely new plugin and is therefore somewhat out of the scope.

Or do you mean the ability of coding/extracting from kanban cards?

**Comment by chrisgrieser** [comment]
okay, coding from canvas files is now supported.

**Comment by brimwats** [comment]
Thank you!! I'm sorry I never circled around back to this to give you an
idea of what I meant but I think you got it! I was also thinking of using
this as a way to code additional documents, PDFs, photos, etc. Appreciate
your labor!

**Comment by chrisgrieser** [comment]
yeah, I just figured that I don't need to understand how coding from a canvas works to enable doing all operations from a canvas file 😆 
(coding nevertheless requires you to be in a markdown note in a canvas.)
