### ISSUE TITLE
[Bug]: Incorrect usage of loadData

### ISSUE THREAD

**Issue by liamcain** [chrisgrieser/obsidian-quadro#2]
### Bug Description

https://github.com/chrisgrieser/obsidian-quadro/blob/772b9c10527ec1974fd42183dc06836fc82f3c40/src/main.ts#L70

This line is incorrect, I missed it before in review, sorry!

```ts
this.settings = Object.assign(DEFAULT_SETTINGS, await this.loadData());
```

This will override DEFAULT_SETTINGS, which I don't think you want.

It should be:
```ts
this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
```

### Obsidian Version

1.5.8

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
oh thx, missed that one. Fixed
