### ISSUE TITLE
[Bug]: Remove References to Dataloom in Template Vault

### ISSUE THREAD

**Issue by brimwats** [chrisgrieser/obsidian-quadro#7]
### Bug Description

As far as I can tell DataLoom was removed for projects; so the references to it should probably be removed. Can list properties have spaces in them now?

### Relevant Screenshot

![image](https://github.com/user-attachments/assets/8ef1a363-016b-4445-b147-41878e031e40)

### To Reproduce

Go to templates in template vault

### Obsidian Version

n/a

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
ah thx, missed updating that part.

Yeah, the example vault isn't using dataloom anymore, so that isn't necessary anymore.
